### PR TITLE
Adding Web3 usage example with TestGreeter

### PR DESCRIPTION
**Pull request by Swoorup**

### CODE REVIEW

**Comment by foxgem** [comment]
@Swoorup Thanks for this PR, can you add `indexed` on `targetContract`?

**Comment by Swoorup** [comment]
@foxgem 

```javascript
 /*
  * @dev Emitted on end of ether split payment transaction
  */
  event EtherPaymentSent(
    address targetContract,
    bytes targetMessage,
    address indexed payer,
    uint256 indexed totalAmount
  );

  /*
  * @dev Emitted on end of ERC20 split payment transaction
  */
  event TokenPaymentSent(
    address targetContract,
    bytes targetMessage,
    address indexed token,
    address indexed payer,
    uint256 indexed totalAmount
  );
```

I can do so for EtherPaymentSend, but can't for `TokenPaymentSent` as indexed is limited to 3 parameters. Which other param should I omit?

**Comment by foxgem** [comment]
@Swoorup please remove `indexed` from `totalAmount`, thanks.

**Comment by Swoorup** [comment]
@foxgem that is merged by https://github.com/Swoorup/eth-batcher-contracts/pull/10

**Pull request merged**
